language: java
jdk:
- oraclejdk8
before_install: git submodule update --init --recursive
install: echo "Building Crutch for 1.10.2"
before_script: find .
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/4.2-rc-2/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/build/distributions/"
  - "$HOME/release/"
script: "./travii/make.sh"
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  file: "$HOME/release/*"
  on:
    repo: SantaGitHub/crutch
    tags: true
